target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'JanusMessageSDK', :path => '../shared'
  target 'iosAppTests' do
         inherit! :search_paths
         pod 'JanusMessageSDK', :path => '../shared'
  end
end
