name: Deploy WIth KMM Bridge Github Workflow


on: [push, pull_request] # or any other event

# Jobs :  https://github.com/touchlab/KMMBridgeGithubWorkflow/blob/main/.github/workflows/faktorybuildautoversion.yml
permissions:
  contents: write
  packages: write

jobs:
  call-external-workflow:
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildautoversion.yml@main
    with:
      # Provide inputs here if the external workflow requires them
      description: 'Deploying with KMM Bridge' # Optional
    secrets:
      # Provide secrets here if the external workflow requires them
      netrcUsername: ${{ secrets.NETRC_USERNAME }}
      netrcPassword: ${{ secrets.NETRC_PASSWORD }}